Set upper bound for Python version
Python 3.14.0 is incompatible with the script's "fastcore" Python package dependency. This causes it to fail when used
with Python 3.14.0:

```
Traceback (most recent call last):
  File "/home/runner/work/my-workflowsawaiting/my-workflowsawaiting/workflowsawaiting/workflowsawaiting.py", line 7, in <module>
    import fastcore.all
  File "/home/runner/.cache/pypoetry/virtualenvs/workflowsawaiting-__LmTFRM-py3.14/lib/python3.14/site-packages/fastcore/all.py", line 3, in <module>
    from .dispatch import *
  File "/home/runner/.cache/pypoetry/virtualenvs/workflowsawaiting-__LmTFRM-py3.14/lib/python3.14/site-packages/fastcore/dispatch.py", line 174, in <module>
    @typedispatch
     ^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/workflowsawaiting-__LmTFRM-py3.14/lib/python3.14/site-packages/fastcore/dispatch.py", line 150, in __call__
    self.d[nm].add(f)
    ~~~~~~~~~~~~~~^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/workflowsawaiting-__LmTFRM-py3.14/lib/python3.14/site-packages/fastcore/dispatch.py", line 93, in add
    else: a0,a1 = _p2_anno(f)
                  ~~~~~~~~^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/workflowsawaiting-__LmTFRM-py3.14/lib/python3.14/site-packages/fastcore/dispatch.py", line 46, in _p2_anno
    hints = type_hints(f)
  File "/home/runner/.cache/pypoetry/virtualenvs/workflowsawaiting-__LmTFRM-py3.14/lib/python3.14/site-packages/fastcore/basics.py", line 347, in type_hints
    if not isinstance(f, typing._allowed_types): return {}
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.14.0/x64/lib/python3.14/typing.py", line 3838, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {attr!r}")
AttributeError: module 'typing' has no attribute '_allowed_types'
```

The problem has been fixed in fastcore@1.8.13, so updating the dependency would be one possible solution. However, this
is a transitive dependency so it might be problematic to update. For this reason, the chosen solution is to set an upper
bound for the Python version in the project metadata.